---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  gitImplementation: libgit2
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  timeout: 1m0s
  url: ssh://APKA2RRFIHV6TU27R7B2@git-codecommit.us-east-1.amazonaws.com/v1/repos/apiservices-manifest

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/test-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

