---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: apiservices
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: dongdgy@amazon.com
        name: dongdgy
    push:
      branch: master
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: apiservices
  update:
    path: ./clusters/test-cluster
    strategy: Setters

