---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: apiservices-dongdgy
  namespace: flux-system
spec:
  image: 724853865853.dkr.ecr.us-east-1.amazonaws.com/apiservices-dongdgy
  interval: 1m0s

