---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: awesomebuilder-for-test
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: awesomebuilder-for-test
  filterTags:
    pattern: '^master-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
     numerical:
      order: asc
